// The emoji grid of the chat (architecture §5.15): 48 chosen emojis, without any library, shown
// in 8 columns. The French name is the accessible name of each button. The Windows shortcut
// Win + . still works in the message field.

export type ChatEmoji = { emoji: string; name: string };

export const CHAT_EMOJIS: readonly ChatEmoji[] = [
  { emoji: "😀", name: "visage souriant" },
  { emoji: "😂", name: "rire aux larmes" },
  { emoji: "😅", name: "sourire gêné" },
  { emoji: "😉", name: "clin d'œil" },
  { emoji: "😍", name: "yeux en cœur" },
  { emoji: "😎", name: "lunettes de soleil" },
  { emoji: "🤔", name: "qui réfléchit" },
  { emoji: "😮", name: "bouche bée" },
  { emoji: "😱", name: "cri d'effroi" },
  { emoji: "😢", name: "larme" },
  { emoji: "😭", name: "en pleurs" },
  { emoji: "😡", name: "en colère" },
  { emoji: "🙄", name: "yeux au ciel" },
  { emoji: "😬", name: "grimace" },
  { emoji: "🤯", name: "tête qui explose" },
  { emoji: "🥳", name: "fête" },
  { emoji: "😴", name: "qui dort" },
  { emoji: "🤞", name: "doigts croisés" },
  { emoji: "👍", name: "pouce levé" },
  { emoji: "👎", name: "pouce baissé" },
  { emoji: "👏", name: "applaudissements" },
  { emoji: "🙌", name: "mains levées" },
  { emoji: "🙏", name: "merci" },
  { emoji: "💪", name: "biceps" },
  { emoji: "👀", name: "yeux" },
  { emoji: "🤝", name: "poignée de main" },
  { emoji: "✌️", name: "victoire" },
  { emoji: "👋", name: "coucou" },
  { emoji: "🎯", name: "cible" },
  { emoji: "🏆", name: "trophée" },
  { emoji: "🥇", name: "médaille d'or" },
  { emoji: "🥈", name: "médaille d'argent" },
  { emoji: "🥉", name: "médaille de bronze" },
  { emoji: "🔥", name: "feu" },
  { emoji: "💯", name: "cent" },
  { emoji: "⭐", name: "étoile" },
  { emoji: "🎉", name: "cotillons" },
  { emoji: "🍀", name: "trèfle" },
  { emoji: "🃏", name: "joker" },
  { emoji: "📈", name: "hausse" },
  { emoji: "📉", name: "baisse" },
  { emoji: "📊", name: "graphique" },
  { emoji: "🎓", name: "diplômé" },
  { emoji: "📚", name: "livres" },
  { emoji: "☕", name: "café" },
  { emoji: "🍕", name: "pizza" },
  { emoji: "❤️", name: "cœur" },
  { emoji: "🚀", name: "fusée" },
];
